modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="mosaic_carpentry" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Mosaic Carpentry" #mandatory
description='''
A mod that adds a mosaic block for every vanilla plank type
'''
[[dependencies.mosaic_carpentry]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.mosaic_carpentry]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
